language: scala
scala:
  - 2.12.8
  - 2.11.12
jdk:
  - oraclejdk8
  - openjdk11
before_install:
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.6.1 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install -f jekyll -v 3.8.5
cache:
  directories:
   - ~/.ivy2
   - ~/.sbt
   - ~/.vendor
script:
  - bash project/build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi
