base_job: &base
  working_directory: ~/repo
  environment:
    TERM: dumb
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
    - run: .circleci/build.sh
    - save_cache:
        paths:
          - ~/.m2
          - ~/.ivy2
          - ~/.sbt
        key: v1-dependencies--{{ checksum "build.sbt" }}

version: 2
jobs:
  build_212_JDK11:
    <<: *base
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.12.10
      COVERAGE: true
  build_212_JDK8:
    <<: *base
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SCALA_VERSION: 2.12.10
      COVERAGE: true
  build_213_JDK11:
    <<: *base
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.13.1
  build_213_JDK8:
    <<: *base
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SCALA_VERSION: 2.13.1
  docs:
    <<: *base
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.12.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-docs-{{ checksum "build.sbt" }}
            - v1-dependencies-docs-
      - run: .circleci/docs.sh
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.gem
          key: v1-dependencies-docs--{{ checksum "build.sbt" }}
  publish212:
    <<: *base
    docker:
    - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.13.1
    steps:
      - checkout
      - run: git fetch --tags
      - run: sbt -mem 2048 ++${SCALA_VERSION} publish
  publish211:
    <<: *base
    docker:
    - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.13.1
    steps:
      - checkout
      - run: git fetch --tags
      - run: sbt -mem 2048 ++${SCALA_VERSION}  publish
  publishDocs:
    <<: *base
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.12.10
    steps:
      - checkout
      - run: git fetch --tags
      - run:
          name: Publish Docs
          command: .circleci/publish-docs.sh
          no_output_timeout: 30m
  release:
    <<: *base
    docker:
    - image: circleci/openjdk:11-jdk
    environment:
      SCALA_VERSION: 2.13.1
    steps:
      - checkout
      - run: git fetch --tags
      - run: sbt -mem 2048 ++${SCALA_VERSION} bintrayRelease

workflows:
  version: 2
  build_test_publish_release:
    jobs:
      - build_212_JDK11
      - build_212_JDK8
      - build_213_JDK11
      - build_213_JDK8
      - docs
      - publishDocs:
          requires:
            - docs
          filters:
            branches:
              only:
               - master
      - publish212:
          requires:
            - build_212_JDK11
            - build_212_JDK8
            - build_213_JDK11
            - build_213_JDK8
            - docs
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - publish211:
          requires:
            - build_212_JDK11
            - build_212_JDK8
            - build_213_JDK11
            - build_213_JDK8
            - docs
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - release:
          requires:
            - publish212
            - publish211
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
